I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 186, in script
    w "I guess we could go to counseling. But it’s a lot of work. Are you
Exception: Sayer 'w' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 186, in script
    w "I guess we could go to counseling. But it’s a lot of work. Are you
  File "/Users/gui/Desktop/renpy-6.99.5-sdk/renpy/ast.py", line 574, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Users/gui/Desktop/renpy-6.99.5-sdk/renpy/ast.py", line 491, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'w' is not defined.

Darwin-14.4.0-x86_64-i386-64bit
Ren'Py 6.99.5.602
IMGD_Project 0.0
